# Site settings
title: Sigerr
email: julien@sigerr.org
description: "Thoughts. Snippets. Life."
baseurl: ""
url: "http://www.sigerr.org"

header-img: "assets/images/theme/home.jpg"
google-analytics: "UA-13064797-1"

twitter_username: julienbourdeau
github_username:  julienbourdeau
linkedin_username:  julienbourdeau
youtube_username:  julienbourdeau

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Build settings
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

exclude: ['README.md', "bower_components", "bower.json", "CNAME", "Gemfile", "Gemfile.lock"]

sass:
    load_paths:
        - _sass
    style: compressed

gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
