# Site settings
title: Sigerr
email: julien@sigerr.org
subtitle: "Thoughts. Snippets. Life."
description: "My thought and life stories as an software engineer who's passionate about open source"
baseurl: ""
url: "http://www.sigerr.org"

image: "assets/images/theme/home.jpg"
google-analytics: "UA-13064797-1"

author:
  twitter: benbalter
  github:  julienbourdeau
  linkedin:  julienbourdeau
  youtube:  julienbourdeau

social:
  name: Julien Bourdeau
  links:
    - https://twitter.com/julienbourdeau
    - https://www.facebook.com/julienbourdeau
    - https://www.linkedin.com/in/julienbourdeau
    - https://plus.google.com/+JulienBourdeau
    - https://github.com/julienbourdeau
    - https://keybase.io/julienbourdeau

google_site_verification: 6PX-IP_XFvIy3-j9-BaW80C9gJcx__oN7Ho429fqTvs

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false

# Build settings
permalink: /:categories/:title/
paginate: 5
paginate_path: "/page:num/"

exclude: ['README.md', "bower_components", "bower.json", "CNAME", "Gemfile", "Gemfile.lock"]

sass:
    load_paths:
        - _sass
    style: compressed

gems:
  - jemoji
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-seo-tag
