# Site settings
title: Sigerr
email: julien@sigerr.org
description: "Thoughts. Snippets. Life."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sigerr.org" # the base hostname & protocol for your site

header-img: "assets/images/theme/home.jpg"
google-analytics: "UA-13064797-1"

twitter_username: julienbourdeau
github_username:  julienbourdeau
linkedin_username:  julienbourdeau
youtube_username:  julienbourdeau

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: "/page:num/"

exclude: ['README.md']

sass:
    load_paths:
        - _sass
        - _bower_components
    style: compressed
